#+TITLE: demonos-core-repo
#+DESCRIPTION: A repository of software for DEMONOS.
#+AUTHOR: DemonKingSwarn

* About demonos-core-repo

demonos-core-repo is a repository of Arch Linux packages that was created primarily for DEMONOS, which is still a work-in-progress and not a real thing yet.

=WARNING:= This repo is not meant for public use yet.  The only reason this repo is public is because it has to be public for me to test it out.

* How to "install" demonos-core-repo

You can add demonos-core-repo to any Arch-based Linux distribution.  Just add the following lines to the end of /etc/pacman.conf:

#+begin_example
[demonos-core-repo]
    SigLevel = Required DatabaseOptional
    Server = https://github.com/DemonKingSwarn/$repo/raw/master/$arch
#+end_example

Then, sync the repositories and update your system with:
#+begin_example
sudo pacman -Syyu
#+end_example

And, then:
#+begin_example
sudo pacman -S name-of-package
#+end_example

=NOTE:= Pacman will complain about importing a PGP key that is either invalid or corrupted.  The problem can be fixed by locally signing the imported key:
#+begin_example
sudo pacman-key --lsign-key C71486C31555B12E
#+end_example

* Important information about Suckless programs
** Suckless software
There are several Suckless programs (or programs Suckless in spirit) in this repo, including:
+ dmenu
+ dwm
+ myst

** Where are the Suckless config files?
Suckless programs are configured by editing the source code and recompiling.  The packages installed from this repo are binary installations, but they do place the source code on your system.  The source code is placed in /opt.  For example, the source code for dwm-distrotube is located at /opt/dwm-demonkingswarn.
